name = "ideal-completion"
version = "0.1.0"
defaultTargets = ["IdealCompletion", "IdealCompletionExamples", "IdealCompletionPrimeIdealExamples"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[lean_lib]]
name = "IdealCompletion"

[[lean_lib]]
name = "IdealCompletionExamples"
roots = ["Examples.IdealCompletion"]

[[lean_lib]]
name = "IdealCompletionPrimeIdealExamples"
roots = ["IdealCompletionPrimeIdealExamples"]
